import Head from "next/head";
import { Header, Feed } from "../components";

export default function IndexPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Feed />
    </div>
  );
}
