import Head from "next/head";
import Header from "../components/Header";
import Feed from "../components/Feed";
import styles from "../styles/Home.module.css";

/* export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Feed />
    </div>
  );
} */

import { useSession } from "next-auth/react";

export default function IndexPage() {
  // `session` will match the returned value of `callbacks.session()` from `NextAuth()`
  const { data: session } = useSession();

  return (
    // Your component
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Feed />
    </div>
  );
}
